INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (1, '<wikicategory_1990s_drama_films>', '1990s drama film');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (2, '<wikicategory_20th-century_actors>', '20th-century actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (3, '<wikicategory_21st-century_actors>', '21st-century actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (4, '<wikicategory_American_criminal_comedy_films>', 'American criminal comedy film');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (5, '<wikicategory_American_film_directors>', 'American film director');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (6, '<wikicategory_Australian_soap_opera_actors>', 'Australian soap opera actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (7, '<wikicategory_Canadian_film_actors>', 'Canadian film actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (8, '<wikicategory_Star_Trek:_Enterprise_characters>', 'Character in Star Trek: Enterprise');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (9, '<wikicategory_2000s_crime_films>', 'Crime film from the 2000s');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (10, '<wikicategory_2000s_drama_films>', 'Drama film from the 2000s ');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (11, '<wikicategory_English_film_actors>', 'English film actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (12, '<wikicategory_Films_directed_by_Quentin_Tarantino>', 'Film directed by Quentin Tarantino');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (13, '<wikicategory_Films_directed_by_Steven_Spielberg>', 'Film directed by Steven Spielberg');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (14, '<wikicategory_Films_directed_by_the_Coen_brothers>', 'Film directed by the Coen Brothers');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (15, '<wikicategory_Films_directed_by_Ridley_Scott>', 'Film directed by Ridley Scott');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (16, '<wikicategory_Films_directed_by_Tim_Burton>', 'Film directed by Tim Burton');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (17, '<wikicategory_HBO_network_shows>', 'HBO network show');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (18, '<wikicategory_Lesbian-related_films>', 'Lesbian-related film');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (19, '<wikicategory_Psychological_thriller_films>', 'Psychological thriller film');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (20, '<wikicategory_Serial_killer_films>', 'Film about serial killer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (21, '<wikicategory_Spaghetti_Western_actors>', 'Spaghetti Western actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (22, '<wikicategory_Space_adventure_films>', 'Film about space adventure');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (23, '<wikicategory_War_epic_films>', 'War epic film');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (24, '<wikicategory_Characters_in_The_Lord_of_the_Rings>', 'Character in The Lord of the Rings');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (25, '<wikicategory_Characters_created_by_Stan_Lee>', 'Character that was created by Stan Lee');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (26, '<wikicategory_Fictional_characters_who_can_turn_invisible>', 'Fictional character who can turn invisible');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (27, '<wikicategory_Filename_extensions>', 'Filename extension');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (28, '<wikicategory_Mythological_places>', 'Mythological place');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (29, '<wordnet_programming_language_106898352>', 'Programming language');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (30, '<wikicategory_Port_cities_and_towns_of_the_Persian_Gulf>', 'Town of the Persian Gulf');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (31, '<wikicategory_African_countries>', 'African country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (32, '<wikicategory_Capitals_in_Africa>', 'Capital in Africa');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (33, '<wikicategory_Capitals_in_Asia>', 'Capital in Asia');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (34, '<wikicategory_Capitals_in_Europe>', 'Capital in Europe');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (35, '<wikicategory_Capitals_in_North_America>', 'Capital in North America');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (36, '<wikicategory_Central_Asian_countries>', 'Central Asian country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (37, '<wikicategory_Countries_of_the_Mediterranean_Sea>', 'Country of the Mediterranean Sea');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (38, '<wikicategory_East_Asian_countries>', 'East Asian country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (39, '<wikicategory_European_countries>', 'European country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (40, '<wikicategory_European_Union_member_economies>', 'European Union member economy');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (41, '<wikicategory_Islamic_holy_places>', 'Holy place in Islam');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (42, '<wikicategory_Holy_cities>', 'Holy city');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (43, '<wikicategory_Member_states_of_the_United_Nations>', 'Member state of the United Nations');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (44, '<wikicategory_Near_Eastern_countries>', 'Near Eastern country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (45, '<wikicategory_Deserts_of_Africa>', 'Desert in Africa');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (46, '<wikicategory_Southeast_Asian_countries>', 'Southeast Asian country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (47, '<wikicategory_States_of_the_United_States>', 'State of the United States');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (48, '<wikicategory_Israeli_film_actors>', 'Israeli film actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (49, '<wikicategory_Israeli_television_actors>', 'Israeli television actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (50, '<wikicategory_Israeli_film_directors>', 'Israeli film director');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (51, '<wikicategory_Hebrew_Bible_cities>', 'City from the Hebrew Bible');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (52, '<wikicategory_Cities_in_Israel>', 'City in Israel');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (53, '<wikicategory_Cities_in_the_West_Bank>', 'City in the West Bank');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (54, '<wikicategory_Research_institutes_in_Israel>', 'Research institution in Israel');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (55, '<wikicategory_Israeli_composers>', 'Israeli composer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (56, '<wikicategory_Israeli_female_singers>', 'Israeli female singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (57, '<wikicategory_Israeli_male_singers>', 'Israeli male singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (58, '<wikicategory_Israeli_musicians>', 'Israeli musician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (59, '<wikicategory_Israeli_pop_singers>', 'Israeli pop singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (60, '<wikicategory_Israeli_record_producers>', 'Israeli records producer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (61, '<wikicategory_Israeli_rock_guitarists>', 'Israeli rock guitarist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (62, '<wikicategory_Israeli_rock_singers>', 'Israeli rock singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (63, '<wikicategory_Assassinated_Israeli_politicians>', 'Assassinated Israeli politician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (64, '<wikicategory_Israeli_children\'s_writers>', 'Israeli children\'s writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (65, '<wikicategory_Israeli_female_models>', 'Israeli female model');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (66, '<wikicategory_Israeli_journalists>', 'Israeli journalist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (67, '<wikicategory_Israeli_male_models>', 'Israeli male model');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (68, '<wikicategory_Israeli_Nobel_laureates>', 'Israeli Nobel laureate');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (69, '<wikicategory_Israeli_non-fiction_writers>', 'Israeli non-fiction writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (70, '<wikicategory_Israeli_novelists>', 'Israeli novelist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (71, '<wikicategory_Israeli_party_leaders>', 'Israeli party leader');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (72, '<wikicategory_Israeli_people_of_Iraqi_origin>', 'Israeli personality of Iraqi origin');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (73, '<wikicategory_Israeli_people_of_Polish_origin>', 'Israeli personality of Polish origin');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (74, '<wikicategory_Israeli_people_of_Yemeni_origin>', 'Israeli personality of Yemeni origin');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (75, '<wikicategory_Israeli_science_fiction_writers>', 'Israeli science fiction writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (76, '<wikicategory_Israeli_short_story_writers>', 'Israeli short story writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (77, '<wikicategory_Israeli_stage_actors>', 'Israeli stage actor');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (78, '<wikicategory_Israeli_comedians>', 'Israeli comedian');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (79, '<wikicategory_LGBT_people_from_Israel>', 'LGBT personality from Israel');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (80, '<wikicategory_Palmach_fighters>', 'Palmach fighter');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (81, '<wikicategory_Rokdim_Im_Kokhavim_participants>', 'Participated in Rokdim Im Kokhavim ');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (82, '<wikicategory_Prime_Ministers_of_Israel>', 'Prime Minister of Israel');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (83, '<wikicategory_Signatories_of_the_Israeli_Declaration_of_Independence>', 'Signatory of the Israeli Declaration of Independence');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (84, '<wikicategory_Beitar_Jerusalem_F.C._players>', 'Beitar Jerusalem F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (85, '<wikicategory_Football_clubs_in_Israel>', 'Football Club in Israel');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (86, '<wikicategory_Israel_international_footballers>', 'Israel international footballer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (87, '<wikicategory_Olympic_bronze_medalists_for_Israel>', 'Israeli athlete who won an Olympic bronze medal');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (88, '<wikicategory_Olympic_swimmers_of_Israel>', 'Israeli olympic swimmer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (89, '<wikicategory_Maccabi_Haifa_F.C._players>', 'Maccabi Haifa F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (90, '<wikicategory_Maccabi_Tel_Aviv_F.C._players>', 'Maccabi Tel Aviv F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (91, '<wikicategory_Maccabiah_Games_gold_medalists>', 'Won a gold medal of the Maccabiah Games');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (92, '<wikicategory_African_American_rappers>', 'African American rapper');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (93, '<wikicategory_Alternative_rock_groups_from_California>', 'Alternative rock group from California');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (94, '<wikicategory_Alternative_rock_groups_from_New_York>', 'Alternative rock group from New York');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (95, '<wikicategory_American_folk_rock_musicians>', 'American folk rock musician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (96, '<wikicategory_American_pop_singers>', 'American pop singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (97, '<wikicategory_American_rock_guitarists>', 'American rock guitarist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (98, '<wikicategory_American_soul_singers>', 'American soul singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (99, '<wikicategory_British_alternative_rock_groups>', 'British alternative rock group');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (100, '<wikicategory_English_New_Wave_musicians>', 'English New Wave musician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (101, '<wikicategory_English_rock_singers>', 'English rock singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (102, '<wikicategory_Female_rock_singers>', 'Female rock singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (103, '<wikicategory_Hip_hop_singers>', 'Hip hop singer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (104, '<wikicategory_Lead_guitarists>', 'Lead guitarist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (105, '<wikicategory_Murdered_musicians>', 'Musician who was murdered ');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (106, '<wikicategory_Synthpop_groups>', 'Synthpop group');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (107, '<wikicategory_20th-century_mathematicians>', '20th-century mathematician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (108, '<wikicategory_Assassinated_United_States_Presidents>', 'Assassinated United States President');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (109, '<wikicategory_English_novelists>', 'English novelist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (110, '<wikicategory_English_science_fiction_writers>', 'English science fiction writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (111, '<wikicategory_German_philosophers>', 'German philosopher');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (112, '<wikicategory_Jewish_American_scientists>', 'Jewish American scientist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (113, '<wikicategory_Jewish_philosophers>', 'Jewish philosopher');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (114, '<wikicategory_Jewish_poets>', 'Jewish poet');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (115, '<wikicategory_Jewish_politicians>', 'Jewish politician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (116, '<wikicategory_Nobel_Peace_Prize_laureates>', 'Nobel Peace Prize laureate');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (117, '<wikicategory_Nonviolence_advocates>', 'Advocate of Nonviolence');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (118, '<wikicategory_The_Voice_judges>', 'One of the Voice judges');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (119, '<wikicategory_The_X_Factor_judges>', 'One of the X Factor judges');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (120, '<wikicategory_Philosophers_of_mind>', 'Philosopher of mind');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (121, '<wikicategory_Presidents_of_the_United_States>', 'President of the United States');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (122, '<wikicategory_2010_FIFA_World_Cup_players>', '2010 FIFA World Cup player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (123, '<wikicategory_Premier_League_clubs>', 'Premier League football club');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (124, '<wikicategory_A.C._Milan_players>', 'A.C. Milan player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (125, '<wikicategory_Basketball_players_from_New_York>', 'Basketball player from New York');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (126, '<wikicategory_Boston_Celtics_players>', 'Boston Celtics player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (127, '<wikicategory_Chelsea_F.C._players>', 'Chelsea F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (128, '<wikicategory_Chicago_Bulls_players>', 'Chicago Bulls player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (129, '<wikicategory_FC_Barcelona_footballers>', 'FC Barcelona football player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (130, '<wikicategory_Los_Angeles_Lakers_players>', 'Los Angeles Lakers player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (131, '<wikicategory_Manchester_United_F.C._players>', 'Manchester United F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (132, '<wikicategory_NBA_Slam_Dunk_Contest_champions>', 'NBA Slam Dunk Contest champion');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (133, '<wikicategory_UEFA_Euro_2008_players>', 'UEFA Euro 2008 player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (134, '<wikicategory_MTV_cartoons>', 'MTV cartoon');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (135, '<wikicategory_Constellations>', 'Constellation (astronomy)');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (136, '<wikicategory_Computer_security_software_companies>', 'Computer security software company');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (137, '<wikicategory_Broadway_musicals>', 'Broadway musical');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (138, '<wikicategory_Fashion_magazines>', 'Fashion magazine');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (139, '<wikicategory_Mythological_kings>', 'Mythological king');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (140, '<wikicategory_Hebrew_Bible_people>', 'Character from the Hebrew Bible');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (141, '<wikicategory_Jewish_ritual_objects>', 'Jewish ritual object');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (142, '<wikicategory_University_towns>', 'University town');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (143, '<wikicategory_Capitals_in_South_America>', 'Capital in South America');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (144, '<wikicategory_Countries_bordering_the_Atlantic_Ocean>', 'Country on the borders of the Atlantic Ocean');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (145, '<wikicategory_Archaeological_sites_in_Iraq>', 'An archaeological site in Iraq');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (146, '<wikicategory_Cities_in_the_Netherlands>', 'City in the Netherlands');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (147, '<wikicategory_Mediterranean_port_cities_and_towns_in_Italy>', 'Mediterranean port city in Italy');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (148, '<wikicategory_Neighbourhoods_of_Barcelona>', 'Neighbourhood in Barcelona');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (149, '<wikicategory_European_seas>', 'European sea');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (150, '<wikicategory_Arabic-speaking_countries_and_territories>', 'Arabic-speaking territory');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (151, '<wikicategory_Ethnic_groups_in_Europe>', 'European ethnic group');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (152, '<wikicategory_Software_companies_of_Israel>', 'Israeli software company');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (153, '<wikicategory_Neighbourhoods_of_Jerusalem>', 'Neighbourhood in Jerusalem');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (154, '<wikicategory_Israeli_settlements>', 'Israeli settlement');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (155, '<wikicategory_Kokhav_Nolad_contestants>', 'Participated in Kokhav Nolad');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (156, '<wikicategory_Israeli_mathematicians>', 'Israeli mathematician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (157, '<wikicategory_Maccabi_Petah_Tikva_F.C._players>', 'Maccabi Petah Tikva F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (158, '<wikicategory_Hapoel_Tel_Aviv_F.C._players>', 'Hapoel Tel Aviv F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (159, '<wikicategory_Bnei_Sakhnin_F.C._players>', 'Bnei Sakhnin F.C. player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (160, '<wikicategory_Port_cities_and_towns_of_the_Baltic_Sea>', 'Port city of the Baltic Sea');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (161, '<wikicategory_Coastal_cities_and_towns_in_Sweden>', 'Coastal city in Sweden');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (162, '<wikicategory_French-speaking_countries>', 'French-speaking country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (163, '<wikicategory_Southern_Mediterranean_countries>', 'Southern Mediterranean country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (164, '<wikicategory_Least_developed_countries>', 'Least developed country');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (165, '<wikicategory_Middle_Eastern_countries>', 'Country in the Middle East');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (166, '<wikicategory_Member_states_of_NATO>', 'Member state of NATO');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (167, '<wikicategory_Active_volcanoes_of_Indonesia>', 'Active volcano in Indonesia');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (168, '<wikicategory_Cities_in_Iran>', 'City in Iran');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (169, '<wikicategory_Squares_in_Tel_Aviv>', 'A Square in Tel Aviv');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (170, '<wikicategory_Ancient_cities>', 'An ancient city');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (171, '<wikicategory_Ancient_Greek_cities>', 'Ancient Greek city');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (172, '<wikicategory_Roman_sites_in_Egypt>', 'Roman site in Egypt');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (173, '<wikicategory_Lakes_of_New_York>', 'A lake in New York');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (174, '<wikicategory_Rivers_of_Romania>', 'A river in Romania');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (175, '<wikicategory_Coastal_cities_in_Australia>', 'Coastal city in Australia');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (176, '<wikicategory_Cities_in_Colorado>', 'City in Colorado');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (177, '<wikicategory_Port_cities_in_Africa>', 'Port city in Africa');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (178, '<wikicategory_World_Heritage_Sites_in_Italy>', 'World Heritage Site in Italy');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (179, '<wikicategory_Israeli_generals>', 'Israeli general');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (180, '<wikicategory_Israeli_activists>', 'Israeli activist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (181, '<wikicategory_Israeli_comics_writers>', 'Israeli comics writer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (182, '<wikicategory_Israeli_literary_critics>', 'Israeli literary critic');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (183, '<wikicategory_Israeli_jazz_musicians>', 'Israeli jazz musician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (184, '<wikicategory_Israeli_musical_groups>', 'Israeli musical group');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (185, '<wikicategory_Israeli_women_in_politics>', 'Israeli woman in politics');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (186, '<wikicategory_Israeli_pacifists>', 'Israeli pacifist');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (187, '<wikicategory_Israeli_female_tennis_players>', 'Israeli female tennis player');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (188, '<wikicategory_Mapai_politicians>', 'Mapai politician');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (189, '<wikicategory_Mayors_of_Haifa>', 'Mayor of Haifa');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (190, '<wikicategory_Mayors_of_Tel_Aviv-Yafo>', 'Mayor of Tel Aviv-Yafo');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (191, '<wikicategory_Mayors_of_Jerusalem>', 'Mayor of Jerusalem');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (192, '<wikicategory_Michael_Jackson_songs>', 'One of Michael Jackson songs');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (193, '<wikicategory_Israeli_television_presenters>', 'Israeli television presenter');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (194, '<wikicategory_Israeli_film_producers>', 'Israeli film producer');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (195, '<wikicategory_Israeli_diplomats>', 'Israeli diplomat');
INSERT INTO DEFINITIONS (id, yago_type, definition) VALUES (196, '<wikicategory_Israeli_films>', 'Israeli film');