INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<diedOnDate>', 'That person died on ?', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<wasBornOnDate>', 'That person was born on ?', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<wasCreatedOnDate>', 'Was created on ?', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasNumberOfPeople>', 'Populated by ? people', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasMotto>', 'Its motto is ?', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasPages>', 'Has ? pages', null);
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<actedIn>', 'Participated in ?', 'Production in which ? participated');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<created>', 'Created ?', 'Was created by ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<directed>', 'Directed ?', 'Was directed by ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasCapital>', 'Its capital is ?', 'Captial of ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasChild>', 'Parent of ?', 'Child of ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasCurrency>', 'Its currency is ?', 'The currency of ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<happenedIn>', 'It happened in ?', '? happened there');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasOfficialLanguage>', 'Its official language is ?', 'The official language of ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<holdsPoliticalPosition>', '?', 'The political position ? holds');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<isInterestedIn>', 'Person who is interested in ?', '? is interested in it');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<isMarriedTo>', 'Married to ?', 'Married to ?');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<playsFor>', 'Plays for ?', '? plays for it');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<wasBornIn>', 'Was born in ?', '? was born there');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<hasWonPrize>', 'Has won the ?', '? has won it');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<wroteMusicFor>', 'Wrote music for ?', '? wrote its music');
INSERT INTO predicates (yago_predicate, subject_str, object_str) VALUE ('<worksAt>', 'Works at ?', '? works there');